# Generated by Django 4.1.1 on 2022-12-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0002_remove_users_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image_url',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
