# Generated by Django 4.1.1 on 2023-03-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0005_chatcontentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcontentmodel',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='chatcontentmodel',
            name='chatbot_name',
            field=models.ManyToManyField(to='ChatBotApp.chatbotmodel'),
        ),
    ]
