# Generated by Django 4.1.1 on 2023-03-27 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0007_chatcontentmodel_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_bot_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]

#          migrations.RenameField(
#             model_name='chatcontentmodel',
#             old_name='content',
#             new_name='message',
#         ),
#         migrations.RemoveField(
#             model_name='chatcontentmodel',
#             name='chatbot_name',
#         ),
#         migrations.RemoveField(
#             model_name='chatcontentmodel',
#             name='user_name',
#         ),
#         migrations.AddField(
#             model_name='chatcontentmodel',
#             name='chat_bot_id',
#             field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ChatBotApp.chatbotmodel'),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='chatcontentmodel',
#             name='is_human',
#             field=models.BooleanField(default=True),
#         ),
#         migrations.AddField(
#             model_name='chatcontentmodel',
#             name='user_id',
#             field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='chatcontentmodel',
#             name='chat_id',
#             field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ChatBotApp.chatsmodel'),
#             preserve_default=False,
#         ),