# Generated by Django 4.1.1 on 2023-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatBotApp', '0008_chatsmodel_rename_content_chatcontentmodel_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_human', models.BooleanField(default=True)),
                ('chatbot_name', models.ManyToManyField(to='ChatBotApp.chatbotmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='ChatContentModel',
        ),
    ]
